### ISSUE TITLE
Error on use in Yii version 2.0.13-dev

### ISSUE THREAD

**Issue by msarocha** [edgardmessias/yii2-firebird#10]
Hi,
When I use your great component in the Yii version 2.0.13-dev I have the following error:
` PHP Warning – yii\base\ErrorException
Declaration of edgardmessias\db\firebird\QueryBuilder::prepareInsertSelectSubQuery($columns, $schema) should be compatible with yii\db\QueryBuilder::prepareInsertSelectSubQuery($columns, $schema, $params = Array)`

The apparent solution is to adjust your class:
`protected function prepareInsertSelectSubQuery($columns, $schema)
(...)
return parent::prepareInsertSelectSubQuery($columns, $schema);`

... to that of:
`protected function prepareInsertSelectSubQuery($columns, $schema, $params = [])
(...)
return parent::prepareInsertSelectSubQuery($columns, $schema, $params);`

Thanks!

**Comment by mariuz** [comment]
Fixed with https://github.com/edgardmessias/yii2-firebird/commit/4c085819934d2af76f029736d4dd0919bf9ea161

@msarocha 
please use the master version 

@edgardmessias can be closed

**Comment by edgardmessias** [comment]
Thanks @mariuz
