### ISSUE TITLE
Working with Firebird transactions

### ISSUE THREAD

**Issue by EndErr** [edgardmessias/yii2-firebird#16]
Is there a way how to work with Firebird transactions?

**Comment by edgardmessias** [comment]
Could you give more explanation?
`yii2-firebird` has support to transactions

**Comment by EndErr** [comment]
In a desktop application I use to use transactions on insert/update/view.
For example, for reports I use isolation snapshot.
For reading in datasets i use read_commited.

**Comment by edgardmessias** [comment]
See https://www.yiiframework.com/doc/guide/2.0/en/db-active-record#transactional-operations

**Comment by EndErr** [comment]
How about isolations? Is  there a way to tel firebird server that a transaction is in snapshot or read_commited?

**Comment by edgardmessias** [comment]
See in the Yii2 documentation
