### ISSUE TITLE
SQLSTATE[HY000]: General error: -502 Cursor is not open 

### ISSUE THREAD

**Issue by lesha724** [edgardmessias/yii2-firebird#17]
Hi, sorry for my English.  I have some problem, when I try insert new ActiveRecord model:

"name": "Exception",
"message": "SQLSTATE[HY000]: General error: -502 Cursor is not open ",
"code": "HY000",
"type": "PDOException",
"file": "yiisoft\\yii2\\db\\Command.php"

And that is only on php5 (5.6.31), on php7 I haven't problem (I try on 7.1.9 ). Firebird 3.0.3.32900. 
And if I try insert by `createCommand` that works fine.

edgardmessias/yii2-firebird: 0.10
yiisoft/yii2: 2.0.15.1

**Comment by edgardmessias** [comment]
Please, paste the table structure.
Has a blob type column?

**Comment by lesha724** [comment]
No, It hasn't blob type.
I create test structure:

```sql
CREATE TABLE TEST2 (
    FIELD1  INTE /* INTE = INTEGER DEFAULT 0 NOT NULL */,
    FIELD2  VAR100 NOT NULL /* VAR100 = VARCHAR(100) DEFAULT '' NOT NULL */,
    FIELD3  VAR35 /* VAR35 = VARCHAR(35) DEFAULT '' NOT NULL */,
    FIELD4  DAT_CURRENT_TIMESTAMP /* DAT_CURRENT_TIMESTAMP = DATE DEFAULT current_timestamp NOT NULL */,
    FIELD5  DAT /* DAT = DATE */
);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TEST2 ADD CONSTRAINT PK_TEST2 PRIMARY KEY (FIELD2);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE TEST2 ADD CONSTRAINT FK_TEST2_1 FOREIGN KEY (FIELD1) REFERENCES TEST1 (T1) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE TEST1 (
    T1  INTE NOT NULL /* INTE = INTEGER DEFAULT 0 NOT NULL */,
    T2  VAR35 /* VAR35 = VARCHAR(35) DEFAULT '' NOT NULL */
);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TEST1 ADD CONSTRAINT PK_TEST1 PRIMARY KEY (T1);
```

I try insert into `test2`

```php
<?php 

$model = new \app\models\Test2();
$model->field1 = 1; //some id from table test1
$model->field2 = 'wqeqwsdzcdczzscxzzx';
$model->field3 = 'sdsfsdsdcds';

$model->save();
```

**Comment by edgardmessias** [comment]
@lesha724, the problem is not in the extension, but in "pdo_firebird"

See this BUG: https://bugs.php.net/bug.php?id=72931

When you use "ActiveRecord", the query has "RETURNING" clause

You can try apply the solution: https://github.com/php/php-src/pull/2230

**Comment by lesha724** [comment]
In yii1 I didn`t have this error in same php and firebird...

**Comment by edgardmessias** [comment]
@lesha724, your primary key is autoincrement?

**Comment by lesha724** [comment]
@edgardmessias, no, I used generator and I tried insert with const value in field with primary key too.

**Comment by edgardmessias** [comment]
@lesha724, the problem is https://bugs.php.net/bug.php?id=72931, not the this extension.

In commeted a alternative solution, to change
```sql
INSERT INTO animal (type) VALUES ('cat') RETURNING id
```
To
```sql
EXECUTE block 
RETURNS (id INTEGER)
AS
BEGIN
    INSERT INTO animal (type) VALUES ('cat') RETURNING id INTO id;
    SUSPEND;
END
```

And work with PHP 5.6 and Firebird 3

**Comment by lesha724** [comment]
Why in yii1 it works fine?

**Comment by edgardmessias** [comment]
Because yii1 not need "RETURNING" clause

**Comment by edgardmessias** [comment]
@lesha724. debug your code and see the final SQL

**Comment by lesha724** [comment]
I saw. Yii1 use [lastInsertId](http://www.php.net/manual/en/function.PDO-lastInsertId.php). Thanks

**Comment by edgardmessias** [comment]
@lesha724, the "pdo_firebird" not has support to "lastinsertid"

**Comment by lesha724** [comment]
Yes, i [see ](https://github.com/robregonm/YiiFirebird/blob/8a21e2b5f4d745b27f11783bcb9d32e015f01184/CFirebirdCommandBuilder.php#L29)
