### ISSUE TITLE
Column names

### ISSUE THREAD

**Issue by MixMe** [edgardmessias/yii2-firebird#19]
Hi, my column name can be like: ClienID or Number, previous developer use Camel-style. How can i work with this extension, this extension make all column names is automatically uppercase on query?

**Comment by edgardmessias** [comment]
For unquoted columns names in database, the extension send the column name with lower case, without quote (`ClientID -> client_id`).
For quoted column names in database, send quoted column name (`ClientID -> "ClientID"`)

The real problem is the firebird store all non quoted columns with UPPERCASE. To map with YII2, I change all to lowercase if is non quoted.

**Comment by MixMe** [comment]
My model are generated with GII, GII name all attributes lowercase, where i need to change to "ClientID", on SearchModel ?

**Comment by edgardmessias** [comment]
Sorry, current version of extension work only lowercase

**Comment by edgardmessias** [comment]
You can use virtual attributes:

```php
public function getClientID(){
  return $this->attributes['clientid'];
}
public function setClientID($val){
  $this->attributes['clientid'] = $val;
}

$model->ClientID = 123;
echo $model->ClientID;

```

**Comment by MixMe** [comment]
Right now i get error on GridView sorting(on click on column name): 
PDOException: SQLSTATE[HY000]: General error: -206 Dynamic SQL Error SQL error code = -206 Column unknown CLIENTID At line 1, column 43 in D:\Git\laragon\www\vendor\yiisoft\yii2\db\Command.php:261
I think because column name is not "CLIENTID" but "ClientID"

**Comment by MixMe** [comment]
how to disable this uppercase?

**Comment by edgardmessias** [comment]
It's not simple, but I'll give you some instructions:

Edit the `Schema.php`, replace all `strtolower` with your function to detect corrent column name
Edit `quoteSimpleTableName` and `quoteSimpleColumnName` to quote correct columns names

**Comment by MixMe** [comment]
Sorry column name is not uppercase is lowercase:
![error](https://user-images.githubusercontent.com/3535911/45179774-1eca3280-b222-11e8-9ff9-1502d245fb26.PNG)

But i need first latter uppercase

**Comment by MixMe** [comment]
With table name was same problem, but after i change 

  public static function tableName()
    {
        return 'records' to return '"Records"';
    }
problem was solved

**Comment by MixMe** [comment]
https://github.com/edgardmessias/yii2-firebird/issues/19#issuecomment-419208748
Solved ! thx ;)
