### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by mmagdiel** [edgardmessias/yii2-firebird#5]
I executed php composer.phar require --prefer-dist "edgardmessias/yii2-firebird:*" and the console show me this...

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - edgardmessias/yii2-firebird 0.8.1 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.8.0 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.7.3 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.7.2 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.7.1 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.7.0 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.6.0 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.5.0 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.4.0 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.3.0 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.2.0 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.1.1 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - edgardmessias/yii2-firebird 0.1.0 requires ext-pdo_firebird \* -> the requested PHP extension pdo_firebird is missing from your system.
    - Installation request for edgardmessias/yii2-firebird \* -> satisfiable by edgardmessias/yii2-firebird[0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php5/cli/php.ini
    - /etc/php5/cli/conf.d/05-opcache.ini
    - /etc/php5/cli/conf.d/10-pdo.ini
    - /etc/php5/cli/conf.d/20-json.ini
    - /etc/php5/cli/conf.d/20-mysql.ini
    - /etc/php5/cli/conf.d/20-mysqli.ini
    - /etc/php5/cli/conf.d/20-pdo_mysql.ini
    - /etc/php5/cli/conf.d/20-readline.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

y dont know the reason. Can help please?

**Comment by edgardmessias** [comment]
Check in your PHP has `pdo_firebird` enabled. You can execute this command to check `php -m | grep -i pdo`

See this: http://mapopa.blogspot.com.br/2009/04/php5-and-firebird-pdo-on-ubuntu-hardy.html

**Comment by edgardmessias** [comment]
@magdielikari, solved?
