### ISSUE TITLE
Can you help me

### ISSUE THREAD

**Issue by bugzzilla** [edgardmessias/yii2-firebird#6]
I install your ext., add db section in my web.php, but its not working

When i try use gii, i see
**Connection does not support reading schema information for 'firebird' DBMS**

What can i do with db.php ?

**Comment by edgardmessias** [comment]
@bugzzilla , you can show your db.php?

**Comment by bugzzilla** [comment]
Sorry, I solved the problem. I simple replace my db.php with your config, and it worked. 

```
  //  'class' => 'yii\db\Connection',
  //  'dsn' => _PDO_FIREBIRD_DSN_,
  //  'username' => _PDO_FIREBIRD_USER_,
  //  'password' => _PDO_FIREBIRD_PASSW_,
    'charset' => 'utf8',
           'class' => 'edgardmessias\db\firebird\Connection',
            'dsn' => _PDO_FIREBIRD_DSN_,
            'username' => _PDO_FIREBIRD_USER_,
            'password' => _PDO_FIREBIRD_PASSW_,
```

At the end of the day the head does not work

**Comment by edgardmessias** [comment]
Great.
