### ISSUE TITLE
Schema (Columns) are not retrieved by ActiveRecord.

### ISSUE THREAD

**Issue by thyseus** [edgardmessias/yii2-firebird#7]
Hey edgardmessias, thanks for this great extension! I got it almost working, but i fail at the last step.

I have this DB configuration:

```
return [
    'class' => 'edgardmessias\db\firebird\Connection',
    'dsn' => 'firebird:dbname=localhost:/home/thyseus/dev/test.fdb;charset=UTF-8',
    'username' => 'SYSDBA',
    'password' => 'sysdba',
];
```

Which is working fine ! Now i have an table called BESTAND_WEB in this database:

```
CREATE TABLE BESTAND_WEB
(
  ID bigint,
  MATCHCODE varchar(30),
  MATNR_K varchar(20),
  BESTELLNR varchar(20),
  EBEZ varchar(50),
  AUFNR char(6),
  EPNR smallint,
  BESTELLT integer,
  SUMPRODUZIERT bigint,
  SUMGELIEFERT bigint,
  SUMLAGER integer,
  LAGERTAGE integer,
  STICHTAG timestamp
);
```

My ActiveRecord model looks like this:

```
   public static function tableName()
    {
        return 'BESTAND_WEB';
    }

    public static function getDb() {
        return Yii::$app->db_firebird;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['EPNR', 'BESTELLT', 'SUMPRODUZIERT', 'SUMGELIEFERT', 'SUMLAGER', 'LAGERTAGE'], 'integer'],
            [['STICHTAG'], 'safe'],
            [['MATCHCODE'], 'string', 'max' => 30],
            [['MATNR_K', 'BESTELLNR'], 'string', 'max' => 20],
            [['EBEZ'], 'string', 'max' => 50],
            [['AUFNR'], 'string', 'max' => 6],
        ];
    }
```

Everything seems to be working fine, but ActiveRecord is not able to retrieve the SCHEMA DEFINITION (columns) from the BESTAND_WEB table.

`Getting unknown property: app\models\BestandwebSearch::ID`

Any Idea how i can debug this issue? 

Thanks a lot in advance !

**Comment by edgardmessias** [comment]
Hello, you need use lowercase for columns and table names.

**Comment by thyseus** [comment]
Hey. Thanks for this Information. I will discuss if this is possible for my current project and will try to enhance your driver to be case-agnostic if necessary !

**Comment by edgardmessias** [comment]
In Firebird, all columns of table names are in uppercase by default. Other databases are lowercase.

You can continue this fork: if you need https://github.com/edgardmessias/yii2-firebird/commits/column_case_support

**Comment by thyseus** [comment]
By the way: Using lowercase columns works fine ! There is no need to adjust this module for my requirements. Thanks a lot.
