### ISSUE TITLE
QueryBuilder issue

### ISSUE THREAD

**Issue by ittaskeu** [edgardmessias/yii2-firebird#9]
QueryBuilder  > buildOrderByAndLimit  > row 182
current: $sql = preg_replace('/^SELECT /i', 'SELECT FIRST ' . (int) $limit . ' SKIP ' . (int) $offset, $sql, $count);
fixed: $sql = preg_replace('/^SELECT /i', 'SELECT FIRST ' . (int) $limit . ' SKIP ' . (int) $offset . ' ', $sql, $count);

**Comment by edgardmessias** [comment]
Fixed in b3095db

**Comment by edgardmessias** [comment]
Thanks @ittaskeu

**Comment by edgardmessias** [comment]
New release [0.9.1](https://github.com/edgardmessias/yii2-firebird/releases/tag/0.9.1)
